#ifndef	imview_HEADER
#define	imview_HEADER

//
// imview_ui.h - User interface object and function declarations.
// This file was generated by `gxv++' from `imview.G'.
// DO NOT EDIT BY HAND.
//

extern Attr_attribute	INSTANCE;

Xv_opaque	imview_FileMenu_create(caddr_t, Xv_opaque);

class imview_mainwindow_objects {

public:
	Xv_opaque	mainwindow;
	Xv_opaque	controls1;
	Xv_opaque	FileButton;

	virtual void	objects_initialize(Xv_opaque);

	virtual Xv_opaque	mainwindow_create(Xv_opaque);
	virtual Xv_opaque	controls1_create(Xv_opaque);
	virtual Xv_opaque	FileButton_create(Xv_opaque);
};
#endif
