//
// imview_ui.cc - User interface object initialization functions.
// This file was generated by `gxv++' from `imview.G'.
// DO NOT EDIT BY HAND.
//

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "imview_ui.h"

//
// Create object `FileMenu' in the specified instance.
//
Xv_opaque
imview_FileMenu_create(caddr_t ip, Xv_opaque owner)
{
	extern Menu_item	load_callback(Menu_item, Menu_generate);
	extern Menu_item	quit_callback(Menu_item, Menu_generate);
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_TITLE_ITEM, "File",
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Load",
			MENU_GEN_PROC, load_callback,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Quit",
			MENU_GEN_PROC, quit_callback,
			NULL,
		MENU_GEN_PIN_WINDOW, owner, "File",
		NULL);
	return obj;
}

//
// Initialize an instance of object `mainwindow'.
//
void
imview_mainwindow_objects::objects_initialize(Xv_opaque owner)
{
	mainwindow = mainwindow_create(owner);
	controls1 = controls1_create(mainwindow);
	FileButton = FileButton_create(controls1);
}

//
// Create object `mainwindow' in the specified instance.
//
Xv_opaque
imview_mainwindow_objects::mainwindow_create(Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, this,
		XV_WIDTH, 82,
		XV_HEIGHT, 38,
		XV_LABEL, "ImView",
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

//
// Create object `controls1' in the specified instance.
//
Xv_opaque
imview_mainwindow_objects::controls1_create(Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, this,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

//
// Create object `FileButton' in the specified instance.
//
Xv_opaque
imview_mainwindow_objects::FileButton_create(Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, this,
		XV_X, 16,
		XV_Y, 8,
		PANEL_LABEL_STRING, "File",
		PANEL_ITEM_MENU, imview_FileMenu_create((caddr_t) this, mainwindow),
		NULL);
	return obj;
}

