#ifndef	voltool_HEADER
#define	voltool_HEADER

//
// voltool_ui.h - User interface object and function declarations.
// This file was generated by `gxv++' from `voltool.G'.
// DO NOT EDIT BY HAND.
//

extern Attr_attribute	INSTANCE;

Xv_opaque	voltool_FileMenu_create(caddr_t, Xv_opaque);
Xv_opaque	voltool_RenderMenu_create(caddr_t, Xv_opaque);

class voltool_mainwindow_objects {

public:
	Xv_opaque	mainwindow;
	Xv_opaque	controls1;
	Xv_opaque	FileButton;
	Xv_opaque	RenderButton;
	Xv_opaque	rendercanvas;

	virtual void	objects_initialize(Xv_opaque);

	virtual Xv_opaque	mainwindow_create(Xv_opaque);
	virtual Xv_opaque	controls1_create(Xv_opaque);
	virtual Xv_opaque	FileButton_create(Xv_opaque);
	virtual Xv_opaque	RenderButton_create(Xv_opaque);
	virtual Xv_opaque	rendercanvas_create(Xv_opaque);
};

class voltool_ImageWindow_objects {

public:
	Xv_opaque	ImageWindow;
	Xv_opaque	canvas1;

	virtual void	objects_initialize(Xv_opaque);

	virtual Xv_opaque	ImageWindow_create(Xv_opaque);
	virtual Xv_opaque	canvas1_create(Xv_opaque);
};
#endif
