#ifndef	xlautoimagehandler_HEADER
#define	xlautoimagehandler_HEADER

//
// xlautoimagehandler_ui.h - User interface object and function declarations.
// This file was generated by `gxv++' from `xlautoimagehandler.G'.
// DO NOT EDIT BY HAND.
//

extern Attr_attribute	INSTANCE;


class xvautoimagehandler_window1_objects {

public:
	Xv_opaque	window1;
	Xv_opaque	canvas1;

	virtual void	objects_initialize(Xv_opaque, char *title, 
					   int xdim, int ydim);

	virtual Xv_opaque	window1_create(Xv_opaque, char *title,
					       int xdim, int ydim);
	virtual Xv_opaque	canvas1_create(Xv_opaque);
};
#endif
